[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "braincontrol"
version = "0.5.0"
description = "Network Control Theory for Neuroimaging Data"
authors = [
    { name = "Johannes Wiesner", email = "joh.wiesner@gmail.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "nctpy==1.0.2",
    "xarray",
    "nilearn>=0.13.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "build",
]

[project.urls]
Homepage = "https://github.com/JohannesWiesner/braincontrol"

[tool.setuptools.packages.find]
where = ["src"]
